BestPractices/Website/Models/Auctions/AuctionViewModel.cs
using System;
using Common;

namespace Website.Models.Auctions
{
    public class AuctionViewModel
    {
        /***** "Copied" fields *****/

        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public ItemCondition Condition { get; set; }
        public string ImageUrl { get; set; }
        public string ThumbnailUrl { get; set; }
        public decimal? CurrentPrice { get; set; }
        public decimal StartingPrice { get; set; }
        public DateTime Created { get; private set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public bool IsFeatured { get; set; }


        /***** "Flattened" fields *****/

        public long CategoryId { get; set; }
        public string CategoryKey { get; set; }
        public string CategoryName { get; set; }

        public string SellerUsername { get; set; }
        public int SellerFeebackPercentage { get; set; }
        public string SellerFeebackPercentageDisplay
        {
            get { return SellerFeebackPercentage + "%"; }
        }

        public string TopBidderUsername { get; set; }



        /***** "Smart" fields *****/

        public string CurrentPriceDisplay
        {
            get
            {
                decimal currentPrice = CurrentPrice ?? StartingPrice;
                return currentPrice.ToString("c");
            }
        }

        public string EndsIn
        {
            get
            {
                var remainingTime = RemainingTime;

                if (EndsToday)
                {
                    if (remainingTime > TimeSpan.FromHours(1))
                        return string.Format("{0} hours, {1} minutes", 
                                             remainingTime.Hours, remainingTime.Minutes);
                    
                    return string.Format("{0} minutes", remainingTime.Minutes);
                }

                return string.Format("{0} days, {1} hours", 
                                        remainingTime.Days, remainingTime.Hours);
            }
        }

        public bool EndsToday
        {
            get { return RemainingTime <= TimeSpan.FromDays(1); }
        }

        public bool HasBids
        {
            get { return CurrentPrice != null; }
        }

        public decimal MinimumBid
        {
            get
            {
                if(CurrentPrice == null)
                    return StartingPrice;

                return (CurrentPrice + .10m).Value;
            }
        }

        public string MinimumBidDisplay
        {
            get { return MinimumBid.ToString("g"); }
        }

        public TimeSpan RemainingTime
        {
            get { return EndTime - DateTime.Now; }
        }
    }
}

BestPractices/Website/Models/Auctions/AuctionsViewModel.cs
using System.Collections.Generic;
using System.Linq;

namespace Website.Models.Auctions
{
    public class AuctionsViewModel
    {
        public int Page { get; set; }
        public int PageSize { get; set; }
        public int TotalAuctionsCount { get; set; }
        public string CategoryName { get; set; }
        public string SearchQuery { get; set; }

        public IEnumerable<AuctionViewModel> Auctions { get; set; }

        public int AuctionsCount
        {
            get { return (Auctions ?? Enumerable.Empty<AuctionViewModel>()).Count(); }
        }
    }
}

BestPractices/Website/Models/Auctions/ListItemRequest.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using Common;
using Website.Filters;

namespace Website.Models.Auctions
{
    public class ListItemRequest
    {
        public int CategoryId { get; set; }

        /// <summary>
        /// Populated by the <see cref="CurrentUsernameValueProvider"/>
        /// </summary>
        public string CurrentUserName { get; set; }

        // Property with the same name as the Auction.SellerUsername
        // so that the Mapper will automatically map it by convention
        public string SellerUsername
        {
            get { return CurrentUserName; }
        }

        [DefaultValue(ItemCondition.New)]
        public ItemCondition Condition { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(maximumLength: 500, MinimumLength = 10)]
        public string Title { get; set; }
        
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public HttpPostedFileBase Image { get; set; }

        [Required]
        [Display(Name = "Starting Price")]
        [DataType(DataType.Currency)]
        [Range(1, double.MaxValue)]
        public decimal StartingPrice { get; set; }

        [Required]
        public int Duration { get; set; }

        public DateTime StartTime
        {
            get { return DateTime.Now; }
        }

        public DateTime EndTime
        {
            get { return StartTime.AddDays(Duration); }
        }


        public ListItemRequest()
        {
            Duration = 5;
            StartingPrice = 1;
        }
    }
}

BestPractices/Website/Controllers/AuctionsController.cs
using System.Web.Mvc;
using AttributeRouting.Web.Mvc;
using AutoMapper;

using Common.DataAccess;
using Website.Extensions;
using Website.Models;
using Website.Models.Auctions;

namespace Website.Controllers
{
    public class AuctionsController : Controller
    {
        private readonly IAuctionRepository _repository;

        public AuctionsController(IAuctionRepository repository)
        {
            _repository = repository;
        }

        [Authorize]
        [HttpPost, Route("auctions/{id}/bids")]
        public ActionResult Bid(int id, decimal amount)
        {
            var auction = _repository.Find(id);

            if (auction == null)
                return HttpNotFound("Auction not found");

            if(auction.CurrentPrice >= amount)
            {
                TempData.ErrorMessage(
                        "Your bid of {0:c} isn't higher than the current bid ({1:c}). Try again!",
                        amount, auction.CurrentPrice);

                return RedirectToAction("Details", new { id = auction.Id });
            }

            auction.PlaceBid(User.Identity.Name, amount);
            _repository.SaveChanges();

            TempData.SuccessMessage(
                "Congratulations - you're the highest bidder at {0:c}!", 
                auction.CurrentPrice);

            return RedirectToAction("Details", new {id});
        }

        [Route("auctions/{id}")]
        public ActionResult Details(int id)
        {
            var auction = _repository.Find(id);

            if (auction == null)
                return HttpNotFound("Auction not found");

            var viewModel = Mapper.DynamicMap<AuctionViewModel>(auction);
            
            return View("Details", viewModel);
        }

        [Route("auctions/{id}/history")]
        public ActionResult History(int id)
        {
            return View("History");
        }
    }
}

BestPractices/Website/Views/Auctions/Auctions.cshtml
@model Website.Models.Auctions.AuctionsViewModel

<table id="auctions" class="table table-hover table-condensed">
    <thead>
        <tr>
            <th colspan="2"><h3>@Model.CategoryName</h3></th>
            <th class="span2">Current Price</th>
            <th class="span3">Ends In</th>
        </tr>
    </thead>

    @foreach (var auction in Model.Auctions)
    {
        <tr class="auction" data-id="@auction.Id">
            <td class="span2">
                <img class="img-polaroid" src="@auction.ThumbnailUrl" />
            </td>
            <td>
                <p class="title">
                    @Html.AuctionLink(auction)
                </p>
                <span class="muted">Condition: @auction.Condition</span>
            </td>
            <td>
                <span class="price">@auction.CurrentPriceDisplay</span>
            </td>
            <td>
                <span class="ends-in @(auction.EndsToday ? "text-warning" : "")" title="@auction.EndTime">
                    @auction.EndsIn
                </span>
            </td>
        </tr>
    }
</table>

BestPractices/Website/Views/Auctions/Details.cshtml
@model Website.Models.Auctions.AuctionViewModel
@{
    ViewBag.Title = Model.Title;
}


@section Title {
    <a href="javascript: history.back()">
        <i class="icon-arrow-left">&nbsp;</i>
        Back to search results
    </a>
}


<div id="auction-info" class="row-fluid">
    
    <div id="images" class="span4">
        <img class="img-polaroid" src="@Model.ImageUrl" />
    </div>
    
    <div class="span8">
        
        <h3 id="auction-title">@Model.Title</h3>
        
        <div id="auction-details" class="row-fluid">
            
            <div class="span8">
                <p class="clearfix">
                    <label class="span3 muted">Condition:</label>
                    <span class="condition">@Model.Condition</span>
                </p>

                <p class="clearfix">
                    <label class="span3 muted">Time left:</label>
                    <span class="ends-in">@Model.EndsIn</span>
                    <small class="muted">(@Model.EndTime)</small>
                </p>
            
                <p class="clearfix">
                    <label class="span3 muted">Seller:</label>
                    <span>@Html.ActionLink(Model.SellerUsername ?? " ", "Seller", "Auctions", new { id = Model.Id }, null)</span>
                    <small class="seller-feedback muted">(@Model.SellerFeebackPercentageDisplay positive feedback)</small>
                </p>

                <div id="bid" class="well well-small">
                    <p class="clearfix">
                        <label class="span3 muted">
                            @(Model.HasBids ? "Current" : "Starting") Bid:
                        </label>
                        <span class="current-price">@Model.CurrentPriceDisplay</span>
                        <span class="pull-right">[@Html.ActionLink("Bid History", "History", "Auctions", new { id = Model.Id }, null)]</span>
                    </p>
                    

                    @using (Html.BeginForm("Bid", "Auctions", new { id = Model.Id }, FormMethod.Post))
                    {
                    <p class="clearfix">
                        <label class="span2 muted">&nbsp;</label>
                        <span class="input-prepend span4">
                            <span class="add-on">$</span>
                            <input name="amount" type="text" required="true" class="input-mini" value="@Model.MinimumBidDisplay">
                        </span>
                        <input type="submit" value="Place Bid" class="btn btn-primary"/>
                    </p>
                }
                </div>
            </div>

            <div class="well well-small span4">
                <ul class="actions">
                    <li class="action"><a href="#"><i class="icon-plus-sign"></i> Add to Watch List</a></li>
                    <li class="action"><a href="#"><i class="icon-user"></i> Save seller</a></li>
                    <li class="action"><a href="#"><i class="icon-exclamation-sign"></i> Report item</a></li>
                </ul>
            </div>

        </div>

    </div>

</div>

<div class="row-fluid">
    <ul class="nav nav-tabs">
    <li class="active">
        <a href="#"><strong>Description</strong></a>
    </li>
    </ul>
    <section id="description">
        @Model.Description
    </section>
</div>

BestPractices/Website/Views/Auctions/ListItem.cshtml
@model Website.Models.ListItemRequest

@{
    ViewBag.Title = "List Item for Sale";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-label">
            <label for="CategoryId">Category</label>
        </div>
        <div class="editor-field">
            @Html.DropDownList("CategoryId", Model.Categories)
            @Html.ValidationMessage("CategoryId")
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartingPrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartingPrice)
            @Html.ValidationMessageFor(model => model.StartingPrice)
        </div>

        <div class="editor-label">
            <label for="Duration">Duration</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Duration) days
            @Html.ValidationMessage("Duration")
        </div>

        <div class="editor-label">
            <label for="Image">Image</label>
        </div>
        <div class="editor-field">
            <input name="image" type="file" />
        </div>

    </fieldset>
    
    <div>
        <input class="btn btn-primary" type="submit" value="List Item" />
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}