BestPractices/Website/Controllers/AuctionsController.cs
using System.Web.Mvc;
using AttributeRouting.Web.Mvc;
using AutoMapper;

using Common.DataAccess;
using Website.Extensions;
using Website.Models;
using Website.Models.Auctions;

namespace Website.Controllers
{
    public class AuctionsController : Controller
    {
        private readonly IAuctionRepository _repository;

        public AuctionsController(IAuctionRepository repository)
        {
            _repository = repository;
        }

        [Authorize]
        [HttpPost, Route("auctions/{id}/bids")]
        public ActionResult Bid(int id, decimal amount)
        {
            var auction = _repository.Find(id);

            if (auction == null)
                return HttpNotFound("Auction not found");

            if(auction.CurrentPrice >= amount)
            {
                TempData.ErrorMessage(
                        "Your bid of {0:c} isn't higher than the current bid ({1:c}). Try again!",
                        amount, auction.CurrentPrice);

                return RedirectToAction("Details", new { id = auction.Id });
            }

            auction.PlaceBid(User.Identity.Name, amount);
            _repository.SaveChanges();

            TempData.SuccessMessage(
                "Congratulations - you're the highest bidder at {0:c}!", 
                auction.CurrentPrice);

            return RedirectToAction("Details", new {id});
        }

        [Route("auctions/{id}")]
        public ActionResult Details(int id)
        {
            var auction = _repository.Find(id);

            if (auction == null)
                return HttpNotFound("Auction not found");

            var viewModel = Mapper.DynamicMap<AuctionViewModel>(auction);
            
            return View("Details", viewModel);
        }

        [Route("auctions/{id}/history")]
        public ActionResult History(int id)
        {
            return View("History");
        }
    }
}

BestPractices/Website/Controllers/SellAnItemController.cs
using System.Web.Mvc;
using AttributeRouting.Web.Mvc;
using AutoMapper;
using Common;
using Common.DataAccess;
using Common.Util;
using Website.Extensions;
using Website.Models;
using Website.Models.Auctions;

namespace Website.Controllers
{
    [Authorize]
    public class SellAnItemController : Controller
    {
        public static readonly string AuctionImagesFolder = "~/Content/auction-images";

        private readonly IAuctionRepository _repository;

        public SellAnItemController(IAuctionRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        [Route("sell")]
        public ActionResult Sell()
        {
            return View("Sell", new ListItemRequest());
        }

        [HttpPost]
        [Route("sell")]
        public ActionResult Sell(ListItemRequest request)
        {
            if (ModelState.IsValid)
            {
                var auction = Mapper.DynamicMap<Auction>(request);

                if (request.Image != null)
                {
                    string imageUrl, thumbnailUrl;

                    new ImageRepository(Server.MapPath(AuctionImagesFolder), Url.Content(AuctionImagesFolder))
                        .SaveImage(request.Image.FileName, request.Image.InputStream,
                                   out imageUrl, out thumbnailUrl);

                    auction.ImageUrl = imageUrl;
                    auction.ThumbnailUrl = thumbnailUrl;
                }

                _repository.Add(auction);
                _repository.SaveChanges();

                TempData.SuccessMessage("Congratulations, your item has been listed for auction!");

                return RedirectToAction("Details", "Auctions", new { id = auction.Id });
            }

            TempData.ErrorMessage("Error listing item - please make sure that you've filled in everything correctly! ");

            return View("Sell", request);
        }
    }
}

BestPractices/Website/Views/Shared/_AlertPane.cshtml
@helper AlertPane(string message, string type) {
    if (message != null)
    {
        <div class="alert alert-@type">
            <button type="button" class="close" data-dismiss="alert">×</button>
            @message
        </div>
    }
}

@AlertPane(TempData.SuccessMessage(), "success")

@AlertPane(TempData.ErrorMessage(), "error")

BestPractices/Website/Views/Shared/_Featured.cshtml
@using Website.Models.Auctions
@model IEnumerable<Website.Models.Auctions.AuctionViewModel>

@functions
{
    IEnumerable<IEnumerable<AuctionViewModel>> GroupedAuctions(IEnumerable<AuctionViewModel> auctions, int groupSize)
    {
        var skip = 0;

        while(skip < auctions.Count())
        {
            var group = auctions.Skip(skip).Take(groupSize);
            skip += groupSize;
            yield return group;
        }
    }
}

<div class="featured">
<h2 class="center">Featured Auctions</h2>
<div id="featured-auctions" class="carousel slide">
    <div class="carousel-inner">
        @{ var first = true; }

        @foreach (var auctions in GroupedAuctions(Model, 4))
        {
            <div class="item @(first ? "active": "")">
                <ul class="unstyled">
                @foreach (var auction in auctions)
                {
                    <li class="auction pull-left" data-id="@auction.Id">
                        <a href="@Url.Action("Details", "Auctions", new { id = auction.Id })">
                        <img class="img-polaroid" src="@auction.ThumbnailUrl" />
                        <div class="title">@auction.Title</div>
                        <div><span class="price label label-success">@auction.CurrentPriceDisplay</span></div>
                        </a>
                    </li>
                }
                </ul>
            </div>
            
            first = false;
        }
    </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#featured-auctions" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#featured-auctions" data-slide="next">&rsaquo;</a>
</div>
</div>

BestPractices/Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@(string.IsNullOrWhiteSpace(ViewBag.Title) ? "" : ViewBag.Title + " |") MVC Auctions</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    @Html.Partial("_Navigation")
    
    <div class="container">
        
        <div id="sub-nav" class="well well-small">
            <div class="clearfix">
                <div class="pull-left">
                    @RenderSection("Title", false)
                </div>
                <div class="pull-right clearfix inline">
                    @Html.Partial("_SearchBar")
                </div>
            </div>
        </div>

        @Html.Partial("_AlertPane")

        @RenderBody()

        <hr class="clearfix" />
        <footer>
            <p>&copy; MVC Auctions @DateTime.Now.Year</p>
        </footer>

    </div>

    @Scripts.Render("~/bundles/global")
    @RenderSection("scripts", required: false)
</body>
</html>

BestPractices/Website/Views/Shared/_Navigation.cshtml
@using Common
<div class="navbar navbar-static-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="@Url.Content("~/")">MVC Auctions</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                @foreach(Category category in ViewBag.Categories)
                {
                    <li>@Html.CategoryLink(category)</li>
                }
                </ul>
            </div>
            <div class="pull-right">
                <ul class="nav">
                    <li>
                        <a href="@Url.Action("Sell", "SellAnItem")">
                            <i class="icon-share"></i>
                            Sell item
                        </a>
                    </li>
                    <li>
                    @if(!User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Sign in", "Login", "Account")
                    }
                    else
                    {
                        <div style="margin: 10px 0 10px 10px;">
                        <i class=" icon-user"></i> 
                        @User.Identity.Name
                        @Html.ActionLink("[logout]", "LogOff", "Account")
                        </div>
                    }
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

BestPractices/Website/Views/Shared/_SearchBar.cshtml
<div id="search" class="clearfix">
    <form action="@Url.Action("Search", "Search")" method="GET" class="form-search">
        <div class="input-append pull-right">
            <input name="query" type="text" value="@ViewBag.Query"
                   class="search-query" placeholder="Search" 
                   autocomplete="off" data-provide="typeahead"
                   data-bind="value: searchQuery"
                 />

            @(Html.CategorySelector(ViewBag.SelectedCategory as long?, 
                                    name: "category", htmlAttributes: new { @class ="span2"},
                                    optionLabel: "All Categories"
                  ))

            <input class="btn" type="submit" value="Search" data-bind="click: search" />
        </div>
    </form>
</div>